model:
  g_model : 'sngan'
  d_model : 'sngan'
  generator: 'convolutional'
  discriminator: 'convolutional'
  g_path : '/nfs/gatsbystor/michaela/projects/kale/exp/rebuttal/sngan_celebA/train/checkpoints_7148478/g_85928.pth'
  d_path : '/nfs/gatsbystor/michaela/projects/kale/exp/rebuttal/sampling_celebA_4/tune_and_fids/checkpoints_1957159/d_best.pth'
  latent_noise: 'gaussian'
  Z_dim : 100
  bn: False
  skipinit: False
  num_blocks: 3