# defaults:
#   - exp : default
#   - cluster: OAR
#   - system: default
#   - logs: default
#   - user: default

defaults:
  - system : default 
  - cluster: OAR
  - launcher: default
  - logs: default
  - metrics: default
  - solver : ASIG
  - data : zeros
  - loss: quadlin
  - transfer: wresnet40x2_artbench10_ta

hydra:
  output_subdir: null
  run:
    dir: .
  sweep:
    dir: .
    subdir: .
  hydra_logging:
    disable_existing_loggers: True
  job_logging:
    disable_existing_loggers: True