logger:
  name: DefaultLogger
  parent_log_dir: ./logs
  forced_log_id: -1
  log_streams_to_file: false
scheduler:
  name: OARScheduler
  cleanup_cmd: "source gpu_setVisibleDevices.sh"
  option_cmd: ["-l core=1,walltime=15:00:00",
        "-t besteffort",
        "-t idempotent",
        "-p gpumem>'16000'"
      ]
  shell_config_cmd: source ~/.bashrc
  shell_path: /bin/bash
  env_cmd: conda activate 'base'

version_manager:
  name: GitVM
  parent_target_work_dir: ./.workdir
  skip_requirements: false
  interactive_mode: true
use_version_manager: false
use_scheduler: false
use_logger: true
