logger:
  name: DefaultLogger
  parent_log_dir: ./logs
  forced_log_id: -1
  log_streams_to_file: false
scheduler:
  name: NoScheduler
  shell_path: ''
  shell_config_cmd: ''
  env_cmd: ''
  cleanup_cmd: ''
  option_cmd: []
version_manager:
  name: GitVM
  parent_target_work_dir: ./.workdir
  skip_requirements: true
  interactive_mode: true
use_version_manager: false
use_scheduler: false
use_logger: true
