# @package cluster
engine: "OAR"
cleanup_cmd: "source gpu_setVisibleDevices.sh"
options:
  hours: 10
  gpumodel: null
  gpumem: null
  besteffort: True
  idempotent: True
  nodes: 1
  cpus: 1
  cluster_name: "thoth"