# @package cluster
engine: "SLURM"
options:
  gpus: 1
  hours: 12
  partition: null
  ntasks: ${cluster.gpus}
  C: "v100-32g"
  cpus_per_task: 10
  hint: "nomultithread"
  gres: "gpu:${launcher.gpus}"
  nodes: 1
  ntasks_per_node: 1
